GET http://localhost:4004/odata/v4/leave-management-srv/employeeRecord

###

POST http://localhost:4004/odata/v4/leave-management-srv/employeeRecord
Content-Type: application/json

{
    "firstName": "Williams",
    "lastName": "Jones",
    "email": "williams.jones@example.com",
    "phoneNumber": "3344556677",
    "countryCode": "+1",
    "dob": "1988-07-25",
    "dateOfJoin": "2018-11-05",
    "department": "Finance",
    "designation": "Financial Analyst",
    "salary": 70000.00,
    "address": "654 Maple St, Springfield, IL",
    "reportingManger": "Linda Taylor"
}


###

PUT http://localhost:4004/odata/v4/leave-management-srv/employeeRecord(email='john.doe@example.com')
Content-Type: application/json

{
    "firstName": "Michael",
    "lastName": "Williams",
    "email": "michael.williams@example.com",
    "phoneNumber": "1122334455",
    "countryCode": "+1",
    "dob": "1992-12-31",
    "designation": "Sales Executive",
    "salary": 60000.00,
    "address": "789 Oak St, Springfield, IL",
    "reportingManger": "Sarah Davis"
}

###
PATCH http://localhost:4004/odata/v4/leave-management-srv/employeeRecord(email='john.doe@example.com')
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe"
}

###
DELETE http://localhost:4004/odata/v4/leave-management-srv/employeeRecord(email='john.doe@example.com')

###
GET http://localhost:4004/odata/v4/leave-management-srv/leaveRequest