GET http://localhost:4004/odata/v4/leave-management-srv/employeeRecord

###

POST http://localhost:4004/odata/v4/leave-management-srv/employeeRecord
Content-Type: application/json

{
    "empID": "EMP00009",
    "firstName": "Liam",
    "lastName": "hernandez",
    "email": "hernandez.hernandez@example.com",
    "phoneNumber": "9012346678",
    "countryCode": "+1",
    "dob": "1987-04-04",
    "dateOfJoin": "2019-02-02",
    "department": "Sales",
    "designation": "Sales Manager",
    "salary": 90000.00,
    "address": "357 Fir St, Springfield, IL",
    "reportingManger": "Michael Smith"
}



###

PUT http://localhost:4004/odata/v4/leave-management-srv/employeeRecord(ernandez@exaemail='liam.hmple.com')
Content-Type: application/json

{
    "empID": "EMP00009",
    "firstName": "Liam",
    "lastName": "Hernandez",
    "phoneNumber": "9012345678",
    "countryCode": "+15",
    "dob": "1987-04-04",
    "dateOfJoin": "2019-02-02",
    "department": "Sales",
    "designation": "Sales Manager",
    "salary": 80000.00,
    "address": "357 Fir St, Springfield, IL",
    "reportingManger": "Michael Smith"
}

###
PATCH http://localhost:4004/odata/v4/leave-management-srv/employeeRecord(email='liam.hernandez@example.com')
Content-Type: application/json

{
    "salary" :50000
}

###
DELETE http://localhost:4004/odata/v4/leave-management-srv/employeeRecord(email='hernandez.hernandez@example.com')

###
GET http://localhost:4004/odata/v4/leave-management-srv/leaveRequest